platform_admin_login:
    path:     /login
    defaults: { _controller: PlatformCoreBundle:Core:login }

platform_admin_login_check:
    pattern: /login_check

platform_admin_logout:
    pattern: /logout

platform_admin_home:
    path:     /
    defaults: { _controller: PlatformCoreBundle:Core:index }

platform_admin_user:
    path:     /user-list
    defaults: { _controller: PlatformCoreBundle:User:index }

platform_user_insertpage:
    path:    /insert-user-form
    defaults: { _controller: PlatformCoreBundle:User:addUserForm }

platform_user_updatepage:
    path:    /update-user-form/{userid}
    defaults: { _controller: PlatformCoreBundle:User:updateUserForm, userid = 0 }

platform_user_delete:
    path:    /delete-user/{userid}
    defaults: {_controller: PlatformCoreBundle:User:deleteUser, userid = 0}

platform_admin_tag:
    path:     /tags
    defaults: { _controller: PlatformCoreBundle:Core:adminTag }

platform_admin_tag_form:
    path:    /tag-edit/{tagid}
    defaults: { _controller: PlatformCoreBundle:Core:adminTagForm, tagid = 0 }

platform_admin_media:
    path:     /medias
    defaults: { _controller: PlatformCoreBundle:Core:adminMedia }

platform_admin_media_form:
    path:    /media-edit/{mediaid}
    defaults: { _controller: PlatformCoreBundle:Core:adminMediaForm, mediaid = 0 }

