platform_client_login:
    path:     /login
    defaults: { _controller: PlatformCoreBundle:Client:login }

platform_client_login_check:
    pattern: /login_check

platform_client_logout:
    pattern: /logout

platform_client_home:
    path:     /
    defaults: { _controller: PlatformCoreBundle:Client:index }


