platform_core_admin:
    resource: "@PlatformCoreBundle/Resources/config/routing_admin.yml"
    prefix:   /management

platform_core_client:
    resource: "@PlatformCoreBundle/Resources/config/routing_client.yml"
    prefix:   /my-client

platform_core_front:
    resource: "@PlatformCoreBundle/Resources/config/routing.yml"
    prefix:   /
